[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
auditd-ebpf = { path = "../auditd-ebpf" }
auditd-ebpf-common = { path = "../auditd-ebpf-common", features = ["user"] }
auditd-ebpf-rules = { path = "../auditd-ebpf-rules" }
aya.workspace = true
clap.workspace = true
