[package]
name = "auditd-ebpf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "auditd-ebpf"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[[test]]
name = "rule_compatibility"
path = "../../tests/integration/rule_compatibility.rs"

[[test]]
name = "output_streams"
path = "../../tests/integration/output_streams.rs"

[[test]]
name = "signals"
path = "../../tests/integration/signals.rs"

[dependencies]
anyhow.workspace = true
auditd-ebpf-common = { path = "../auditd-ebpf-common", features = ["user"] }
auditd-ebpf-rules = { path = "../auditd-ebpf-rules" }
aya.workspace = true
aya-log.workspace = true
clap.workspace = true
hex.workspace = true
hmac.workspace = true
libc.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
